EXERCISE 8.1

Create the following NumPy arrays:  
(a) float from 0.0 to 1.0 step 0.1, shape=(11,),   
(b) int zeros (1 byte) with shape=(5,6),  
(c) complex with shape=(9,), powers of x = complex(0, 1): 1, x, x**2, ..., x**8.   

In [36]:
import numpy as np

a = np.arange(0.0, 1.1, 0.1)
print("a = ", a)


b = np.zeros((5,6),dtype="b")
print("b = \n", b)

x = complex(0,1)
c = np.array([x**i for i in range(0,9)])
print("c = ", c)

a =  [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
b = 
 [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
c =  [ 1.+0.j  0.+1.j -1.+0.j -0.-1.j  1.+0.j  0.+1.j -1.+0.j -0.-1.j  1.+0.j]


EXERCISE 8.2  

(a) Create an arbitrary one dimensional array called v1.  
(b) Create a new array (or a view) v2 which consists of items with odd indices of v1.  
(c) Create a new array (or a view) v3 in backwards ordering from v1.   

In [55]:
v1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype="float")
print(v1)

v2 = v1[1::2]
print(v2)

v3 = v1[::-1]
print(v3)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[1. 3. 5. 7. 9.]
[9. 8. 7. 6. 5. 4. 3. 2. 1. 0.]


EXERCISE 8.3

(a) Create a two dimensional array called m1, shape=(4,5).  
(b) Create a new array (or a view) m2 from m1, in which the elements of each row are in reverse order.  
(c) Create a new array (or a view) m3 from m1, in which the elements of each column are in reverse order.  
(d) Remove the first row, the last row, the first column, and the last column of m1, and create a new array (or a view) m4. 


In [59]:
m1 = np.reshape(np.arange(20), (4,5))
print("m1\n", m1)

m2 = m1[::,::-1]
print("m2\n", m2)

m3 = m1[::-1, ::]
print("m3\n", m3)

m4 = np.delete(np.delete(m1, [0, -1],0), [0, -1], 1)
print("m4\n", m4)

m1
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
m2
 [[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]
m3
 [[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]
m4
 [[ 6  7  8]
 [11 12 13]]
